#!/usr/bin/env sh

# 确保脚本抛出遇到的错误
set -e

language: node_js
node_js:
  - lts/*
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: a03d9a4c8792da260b21cc21b1b3bb55acc6595f # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master